### ISSUE TITLE
setup tasks and timeline

### ISSUE THREAD

**Issue by ayushanand18** [ayushanand18/PyEarthData#1]
## Tasks

+ basic structure
    + [x] create a bare python package
    + [x] add dependencies and add setup.cfg | pyproject.toml

+ getting ready for analysis
    + [x] setup functions and modules for grabbing data from APIs
+ add data access for (all near ocean surface)
    + [ ] CO2 concentration
    + [ ] CO3 2- or carbonate concentration
    + [ ] oxides of nitrogen (NO2)
    + [x] oxides of sulfur (SO2)
    + [ ] oxygen concentration (O2)
    + [ ] heavy metal (if found)
    + [ ] other atmospheric gases (near to the surface of oceans)
    + [x] ocean surface temperature data
    + [ ] eridonite saturation
    + [x] CO
    + [x] water vapour
    + [x] relative humidity
+ get data from
    + [ ] ocean data view

update this issue on-the-go

**Comment by pandey-ankit-22** [comment]
Important Links of Information and Datasets :

1. Digital Earth Viewer  🌎 :
[https://www.digitalearthviewer-glodap.geomar.de/](https://www.digitalearthviewer-glodap.geomar.de/)

3. Specific Ocean Observing System  :
[see](https://www.ocean-ops.org/board)

4. Ocean Data View 🌊:
[url](https://odv.awi.de/data/ocean/)

Useful Datasets (Marked) 🟢 :

![image](https://user-images.githubusercontent.com/102639355/186219485-870e9c08-2dd2-433c-91e0-1082bb0a2cbc.png)

![image](https://user-images.githubusercontent.com/102639355/186221133-84e874c3-58c3-40fc-ad9a-aad150884a20.png)

**Comment by ayushanand18** [comment]
> Important Links of Information and Datasets :
> 
> 1. Digital Earth Viewer  🌎 :
>    https://www.digitalearthviewer-glodap.geomar.de/
> 2. Specific Ocean Observing System  :
>    [see](https://www.ocean-ops.org/board)
> 3. Ocean Data View 🌊:
>    [url](https://odv.awi.de/data/ocean/)
> 
> Useful Datasets (Marked) 🟢 :
> 

This looks good but unfortunately the data is nearly unusable. Let's keep it alongside while we try to figure out other datasets that might be more useful to us.

**Comment by ayushanand18** [comment]
+ [ ] [https://oceandata.earth/data-catalog](https://oceandata.earth/data-catalog)

**Comment by ayushanand18** [comment]
+ [ ] NOAA API salin, temp, bact https://gis.ngdc.noaa.gov/arcgis/rest/services/EnvironmentalMonitoring/HABSOSViewBase/MapServer/4
+ [ ] ICES [https://www.ices.dk/](https://www.ices.dk/) - this one looks promising
+ [ ] IODE (collaborates with NOAA)
+ [ ] https://gis.ngdc.noaa.gov/
+ [ ] maps and services (argis) NOAA https://www.ncei.noaa.gov/maps-and-geospatial-products

3rd party sources
+ [ ] datarade.ai

**Comment by ayushanand18** [comment]
- [ ] SMAP http://iprc.soest.hawaii.edu/users/oleg/oisss/atl/OI_V5.0/
- [ ] GHRSST https://www.ncei.noaa.gov/data/oceans/ghrsst/
- [ ] GHRSST https://www.ghrsst.org/ghrsst-data-services/services/
- [ ] GTSPP https://www.nodc.noaa.gov/gtspp/
- [ ] GCOS https://gcos.wmo.int/en/essential-climate-variables
    + get to know which variables and where to look for them

**Comment by ayushanand18** [comment]
- [x] https://power.larc.nasa.gov/api/temporal/daily/point?parameters=QV2M,RH2M,PRECTOTCORR&community=RE&longitude=77.0000&latitude=2.0000&start=20010101&end=20010331&format=JSON&user=DAV temp data

**Comment by ayushanand18** [comment]
Data Availability NO2 can be grabbed from here. (Initial tests)
+ [ ] https://giovanni.gsfc.nasa.gov/giovanni/#service=TmAvMp&starttime=2004-11-05T00:00:00Z&endtime=2004-11-05T23:59:59Z&data=OMNO2d_003_ColumnAmountNO2CloudScreened
+ [ ] more data can be found at https://giovanni.gsfc.nasa.gov/giovanni/ -> **this is what we were looking for, we can fetch plankton data, chlorophyll a concentration, nitrate, sea salt, aerosol, diffusivity and almost everything from here! But the time range where most data is available is between 2012-2015**. Although there is data that is relatively new but ocean biodiversity data around that period will also be available widely (and perhaps the most widely).

**Comment by ayushanand18** [comment]
Congrats! We have got everything we need, we just need to get it working.

**Comment by pandey-ankit-22** [comment]
National Centers for Environmental Information (NCEI) :

- [ ] [https://www.ncei.noaa.gov/products/satellite-oceanography](Link)
- [ ] Consists of major parameters needed for our research. Also, information and their products on **Effect of surface temperature on Coral Reefs Bleaching** can be found at [https://www.ncei.noaa.gov/about/our-impact/coral-reef-watch](Link). 
- [ ] Link for Interacting Map for Deep-Sea Coral and Sponges in all the oceans, [https://www.ncei.noaa.gov/maps/deep-sea-corals/mapSites.htm](Link)

**Comment by ayushanand18** [comment]
+ [ ] https://earthexplorer.usgs.gov/ useful for extracting information
